version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cart-api-php
    working_dir: /var/www/html/cart-api
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: cart-api-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cart-api
      MYSQL_USER: cart-api
      MYSQL_PASSWORD: cart-api
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
